model: volo_d5_512
pretrained: true
num_classes: 10
img_size: 512
batch_size: 2

# hflip: 0
# vflip: 0
# scale: [0.9, 1.0]  
# ratio: [1.0,1.0]
# color_jitter: 0

opt: momentum
lr: 3e-4 # 1e-2
weight-decay: 1e-4

epochs: 90
sched: step
decay_epochs: 30
decay_rate: 0.1


cutmix: 1.0
reprob: 0.5

native-amp: True

aa: corr-aug

#smoothing: 0.0
